name: Deploy to EC2

on:
  push:
    branches: ['step2']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v3

     - name: Set up JDK 21
       uses: actions/setup-java@v3
       with:
          distribution: 'temurin'
          java-version: 21

     - name: Setup SSH
       uses: webfactory/ssh-agent@v0.6.0
       with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
     - name: Connect to EC2 and execute script
       run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "~/deploy.sh" 
